spring:
  application:
    name: Lakesidehotel
  datasource:
    username: root
    password: Vishw@123
    url: jdbc:mysql://localhost:3306/lakeSide_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

  mail:
    host: smtp.gmail.com
    port: 587
    username: vishw2723@gmail.com
    password: oamhppwuzvpnudqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

auth:
  token:
    expirationTime: 3600000
    secret: MySuperSecureJWTSecretKeyThatIsAtLeast32Chars!!